import * as React from 'react';
import {
  Accordion,
AccordionActions,
AccordionDetails,
AccordionSummary,
Alert,
AlertTitle,
AppBar,
Autocomplete,
Avatar,
AvatarGroup,
Backdrop,
Badge,
BottomNavigation,
BottomNavigationAction,
Box,
Breadcrumbs,
Button,
ButtonBase,
ButtonGroup,
Card,
CardActionArea,
CardActions,
CardContent,
CardHeader,
CardMedia,
Checkbox,
Chip,
CircularProgress,
Collapse,
Container,
CssBaseline,
Dialog,
DialogActions,
DialogContent,
DialogContentText,
DialogTitle,
Divider,
Drawer,
Fab,
Fade,
FilledInput,
FormControl,
FormControlLabel,
FormGroup,
FormHelperText,
FormLabel,
GlobalStyles,
Grid,
Grow,
Hidden,
Icon,
IconButton,
ImageList,
ImageListItem,
ImageListItemBar,
Input,
InputAdornment,
InputBase,
InputLabel,
LinearProgress,
Link,
List,
ListItem,
ListItemAvatar,
ListItemButton,
ListItemIcon,
ListItemSecondaryAction,
ListItemText,
ListSubheader,
LoadingButton,
Masonry,
Menu,
MenuItem,
MenuList,
MobileStepper,
Modal,
NativeSelect,
OutlinedInput,
Pagination,
PaginationItem,
Paper,
Popover,
Popper,
Radio,
RadioGroup,
Rating,
ScopedCssBaseline,
Select,
Skeleton,
Slide,
Slider,
Snackbar,
SnackbarContent,
SpeedDial,
SpeedDialAction,
SpeedDialIcon,
Stack,
Step,
StepButton,
StepConnector,
StepContent,
StepIcon,
StepLabel,
Stepper,
SvgIcon,
SwipeableDrawer,
Switch,
Tab,
TabContext,
Table,
TableBody,
TableCell,
TableContainer,
TableFooter,
TableHead,
TablePagination,
TableRow,
TableSortLabel,
TabList,
TabPanel,
Tabs,
TabScrollButton,
TextField,
Timeline,
TimelineConnector,
TimelineContent,
TimelineDot,
TimelineItem,
TimelineOppositeContent,
TimelineSeparator,
ToggleButton,
ToggleButtonGroup,
Toolbar,
Tooltip,
Typography,
Zoom
} from '@mui/material';



export default function App() {
  return (
    <div>
<Container
  disableGutters={true}
>
  <AppBar
    position="static"
  >
    <Toolbar
      justifyContent="space-between"
    >
      <IconButton
        color="inherit"
        aria-label="Menu"
      >
        <Icon>
          menu
        </Icon>
      </IconButton>
      <Typography
        variant="h5"
        color="inherit"
        fontWeight="bold"
      >
        Dashboard
      </Typography>
      <Badge
        badgeContent="14"
        anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        color="secondary"
        overlap="circular"
      >
        <IconButton
          color="inherit"
        >
          <Icon
            color="inherit"
          >
            notifications
          </Icon>
        </IconButton>
      </Badge>
    </Toolbar>
  </AppBar>
  <Box
    width="100%"
    bgcolor="grey.100"
    padding="20px"
  >
    <Grid
      container={false}
      spacing={2}
      rowSpacing={3}
      paddingBottom="20px"
      item={true}
    >
      <Grid
        item={true}
        xs={12}
        sm={6}
      >
        <Breadcrumbs
          aria-label="breadcrumb"
        >
          <Link
            underline="hover"
            color="inherit"
            href="/"
          >
            Orders
          </Link>
          <Typography
            color="primary.main"
          >
            Offers
          </Typography>
        </Breadcrumbs>
      </Grid>
    </Grid>
    <Grid
      container={true}
      spacing={2}
      columnSpacing={3}
      rowSpacing={3}
      paddingBottom="20px"
      item={false}
    >
      <Grid
        item={true}
        xs={12}
        sm="3"
      >
        <Paper
          elevation={3}
          sx={{ padding: '20px' }}
        >
          <Typography>
            <Typography
              variant="body1"
            >
              New offers
            </Typography>
          </Typography>
          <Typography
            padding="10px"
          >
            <Typography
              variant="h3"
              paddingBottom="5px"
              paddingLeft="10px"
            >
              4,100
            </Typography>
            <Typography
              variant="caption"
              color="success.main"
              paddingLeft="10px"
            >
              +881
            </Typography>
          </Typography>
        </Paper>
      </Grid>
      <Grid
        item={true}
        xs={12}
        sm="3"
      >
        <Paper
          elevation={3}
          sx={{ padding: '20px' }}
        >
          <Typography>
            <Typography
              variant="body1"
            >
              Total offers
            </Typography>
          </Typography>
          <Typography
            padding="10px"
          >
            <Typography
              variant="h3"
              paddingBottom="5px"
              paddingLeft="10px"
              color="success.main"
            >
              2,300
            </Typography>
            <Typography
              variant="caption"
              color="success.main"
              paddingLeft="10px"
            >
              +937
            </Typography>
          </Typography>
        </Paper>
      </Grid>
      <Grid
        item={true}
        xs={12}
        sm="3"
      >
        <Paper
          elevation={3}
          sx={{ padding: '20px' }}
        >
          <Typography>
            <Typography
              variant="body1"
            >
              Total value
            </Typography>
          </Typography>
          <Typography
            padding="10px"
          >
            <Typography
              variant="h3"
              paddingBottom="5px"
              paddingLeft="10px"
              color="success.main"
            >
              $75,930
            </Typography>
            <Typography
              variant="caption"
              color="success.main"
              paddingLeft="10px"
            >
              +$12,975
            </Typography>
          </Typography>
        </Paper>
      </Grid>
      <Grid
        item={true}
        xs={12}
        sm="3"
      >
        <Paper
          elevation={3}
          sx={{ padding: '20px' }}
        >
          <Typography>
            <Typography
              variant="body1"
            >
              Total cost
            </Typography>
          </Typography>
          <Typography
            padding="10px"
          >
            <Typography
              variant="h3"
              paddingBottom="5px"
              paddingLeft="10px"
            >
              $3,300
            </Typography>
            <Typography
              variant="caption"
              color="error.main"
              paddingLeft="10px"
            >
              +2,971
            </Typography>
          </Typography>
        </Paper>
      </Grid>
    </Grid>
    <Grid
      container={true}
      spacing={2}
      columnSpacing={3}
      item={false}
    >
      <Grid
        item={true}
        xs={12}
        sm="5"
        rowSpacing={3}
        columnSpacing={3}
        container={true}
      >
        <Grid
          item={true}
          xs={12}
          sm="12"
        >
          <Card>
            <CardHeader
              color="grey"
              ariaLabel="add"
              title="Jackson McKenzie"
              subheader="Top Seller"
              avatar={
                <Avatar>
                  T
                </Avatar>
              }
              action={
                <IconButton>
                  <Icon>
                    more_vert
                  </Icon>
                </IconButton>
              }
            />
            <CardMedia
              component="img"
              height={100}
              image="https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Cool art"
            />
            <CardContent
              component="div"
            >
              <Typography
                gutterBottom={true}
                variant="body1"
                component="div"
              >
                MacBook Pro 13-inch with M1 Chip (2020)
              </Typography>
              <Typography
                variant="body2"
                color="text.secondary"
              >
                Selling a 13-inch MacBook Pro with Retina display, Intel processor, 8GB RAM, and 256GB SSD. Excellent condition, well-maintained, ...
              </Typography>
            </CardContent>
            <CardActionArea>
              <CardActions>
                <Button
                  size="small"
                  color="primary"
                  variant="text"
                >
                  REVIEW
                </Button>
              </CardActions>
            </CardActionArea>
          </Card>
        </Grid>
        <Grid
          item={true}
          xs={12}
          sm="12"
        >
          <Card>
            <CardHeader
              color="grey"
              ariaLabel="add"
              title="John Tester"
              subheader="Newbie"
              avatar={
                <Avatar>
                  N
                </Avatar>
              }
              action={
                <IconButton>
                  <Icon>
                    more_vert
                  </Icon>
                </IconButton>
              }
            />
            <CardMedia
              component="img"
              height={100}
              image="https://images.unsplash.com/photo-1667525312110-e92e900d4c4e?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Cool art"
            />
            <CardContent
              component="div"
            >
              <Typography
                gutterBottom={true}
                variant="body1"
                component="div"
              >
                iPhone 12 Mini (Purple, 128GB)
              </Typography>
              <Typography
                variant="body2"
                color="text.secondary"
              >
                For sale: Gently used purple iPhone. Sleek, stylish, and fully functional. Unlocked and ready for any carrier.
              </Typography>
              <Container
                disableGutters={true}
              />
            </CardContent>
            <CardActionArea>
              <CardActions>
                <Button
                  size="small"
                  color="primary"
                  variant="text"
                >
                  REVIEW
                </Button>
              </CardActions>
            </CardActionArea>
          </Card>
        </Grid>
        <Grid
          item={true}
          xs={12}
          sm="12"
        >
          <Card>
            <CardHeader
              color="grey"
              ariaLabel="add"
              title="Sophie Newman"
              subheader="Top Seller"
              avatar={
                <Avatar>
                  T
                </Avatar>
              }
              action={
                <IconButton>
                  <Icon>
                    more_vert
                  </Icon>
                </IconButton>
              }
            />
            <CardMedia
              component="img"
              height={100}
              image="https://images.unsplash.com/photo-1494698853255-d0fa521abc6c?q=80&w=1228&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="Cool art"
            />
            <CardContent
              component="div"
            >
              <Typography
                gutterBottom={true}
                variant="body1"
                component="div"
              >
                SET: MacBook Pro 13", iPhone 12, Watch.
              </Typography>
              <Typography
                variant="body2"
                color="text.secondary"
              >
                Selling a trio of tech treasures in chic jet black! Includes a MacBook Pro 13", an iPhone 12, and a matching smartwatch.
              </Typography>
              <Container
                disableGutters={true}
              />
            </CardContent>
            <CardActionArea>
              <CardActions>
                <Button
                  size="small"
                  color="primary"
                  variant="text"
                >
                  REVIEW
                </Button>
              </CardActions>
            </CardActionArea>
            <Container
              disableGutters={true}
            />
          </Card>
        </Grid>
      </Grid>
      <Grid
        item={true}
        xs={12}
        sm="7"
      >
        <Table>
          <TableHead>
            <TableRow
              selected={false}
            >
              <TableCell>
                <Typography
                  variant="body2"
                  fontWeight="bold"
                >
                  ORDER ID
                </Typography>
              </TableCell>
              <TableCell>
                <Typography
                  variant="body2"
                  fontWeight="bold"
                >
                  RETAILER NAME
                </Typography>
              </TableCell>
              <TableCell>
                <Typography
                  variant="body2"
                  fontWeight="bold"
                >
                  TYPE
                </Typography>
              </TableCell>
              <TableCell>
                <Typography
                  variant="body2"
                  fontWeight="bold"
                >
                  VALUE
                </Typography>
              </TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Rob Smith
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $1,200
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Jack Back
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $5,700
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Chris McEvans
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $5,700
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Rob Smith
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $320
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Rob Smith
              </TableCell>
              <TableCell>
                CASH
              </TableCell>
              <TableCell>
                $900
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Jack Back
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $5,700
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Robert Turner
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $2,400
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Rob Smith
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $1,200
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Rob Smith
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $1,200
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Hugh Jackson
              </TableCell>
              <TableCell>
                CRASH
              </TableCell>
              <TableCell>
                $5,700
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Jack Back
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $1,290
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Rob Smith
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $860
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Mary Williams
              </TableCell>
              <TableCell>
                CRASH
              </TableCell>
              <TableCell>
                $1,200
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Kate Beck
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $5,700
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Jack Back
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $5,700
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                123456
              </TableCell>
              <TableCell>
                Rob Smith
              </TableCell>
              <TableCell>
                CREDIT
              </TableCell>
              <TableCell>
                $1,200
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </Grid>
    </Grid>
  </Box>
</Container>    </div>
  );
}
